### ISSUE TITLE
It´s not working on Sense setember_2017.

### ISSUE THREAD

**Issue by pbergo** [websy85/sense-tube-map-extension#1]
Hello,

It´s not working on Qlik Sense. I tested since 3.2 SR4 until setember_2017.

Follow the error point using setember_2017.

![image](https://user-images.githubusercontent.com/16706028/32242699-9e8da180-be5a-11e7-864b-c6e812529ba5.png)

![image](https://user-images.githubusercontent.com/16706028/32242753-bd55417c-be5a-11e7-8804-6c7e9d25c1b0.png)

Tks,

**Comment by websy85** [comment]
Hi @pbergo, 

Thanks for pointing this out. It's been a while since I tested this extension.
It should be working again now and I've improved the code behind it quite a lot as well. It still needs some work to make it more flexible but it should at least work again now.

Thanks
Nick
